<?php
$showmsg = array(
    'main' => '回論譠首頁',
    'title' => '私服論譠',
    'register' => '註冊',
    'login' => '登入',
    'logout' => '登出',
    'changepassword' => '修改密碼',
    'recoverpassword' => '忘記密碼',
    'imformation' => '資料查詢',
    'download' => '下載專區',
);

$language_short = array(
    'Armenian' => 'Հայերէն',
    'Azerbaijani' => 'Azərbaycanca',
    'Bangla' => 'বাংলা',
    'Brazilian Portuguese' => 'Português',
    'Bulgarian' => 'Български',
    'Catalan' => 'Català',
    'Chinese simplified' => '簡体中文',
    'Chinese traditional' => '繁體中文',
    'Czech' => 'Čeština',
    'Danish' => 'Dansk',
    'Dutch' => 'Nederlands',
    'English' => 'English',
    'English (United Kingdom)' => 'English (United Kingdom)',
    'Estonian' => 'Eesti',
    'Finnish' => 'Suomi',
    'French' => 'Français',
    'Galician' => 'Galego',
    'German' => 'Deutsch',
    'Greek' => 'Ελληνικά',
    'Hungarian' => 'Magyar',
    'Indonesian' => 'Bahasa Indonesia',
    'Interlingua' => 'Interlingua',
    'Italian' => 'Italiano',
    'Japanese' => '日本語',
    'Korean' => '한국어',
    'Lithuanian' => 'Lietuvių',
    'Norwegian' => 'Norsk',
    'Polish' => 'Polski',
    'Portuguese' => 'Português',
    'Romanian' => 'Română',
    'Russian' => 'Русский',
    'Serbian (latin)' => 'Srpski',
    'Sinhala' => 'සිංහල',
    'Slbanian' => 'Shqip',
    'Slovak' => 'Slovenčina',
    'Slovenian' => 'Slovenščina',
    'Spanish' => 'Español',
    'Swedish' => 'Svenska',
    'Turkish' => 'Türkçe',
    'Ukrainian' => 'Українська',
    'Vietnamese' => 'Tiếng Việt',
);

$language = array(
    'af' => '南非語',
    'sq' => '阿爾巴尼亞語',
    'ar-ae' => '阿拉伯語-阿拉伯聯合大公國',
    'ar-bh' => '阿拉伯語-巴林',
    'ar-dz' => '阿拉伯語-阿爾及利亞',
    'ar-eg' => '阿拉伯語-埃及',
    'ar-iq' => '阿拉伯語-伊拉克',
    'ar-jo' => '阿拉伯語-約旦',
    'ar-kw' => '阿拉伯語-科威特',
    'ar-lb' => '阿拉伯語-黎巴嫩',
    'ar-ly' => '阿拉伯語-利比亞',
    'ar-ma' => '阿拉伯語-摩洛哥',
    'ar-om' => '阿拉伯語-阿曼',
    'ar-qa' => '阿拉伯語-卡達',
    'ar-sa' => '阿拉伯語-沙烏地阿拉伯',
    'ar-sy' => '阿拉伯語-敘利亞',
    'ar-tn' => '阿拉伯語-突尼西亞',
    'ar-ye' => '阿拉伯語-葉門',
    'eu' => '巴斯克語',
    'be' => '白俄羅斯語',
    'bg' => '保加利亞語',
    'ca' => '加泰隆尼亞語',
    'zh' => '中文',
    'zh-cn' => '中文-中國大陸',
    'zh-hk' => '中文-香港',
    'zh-sg' => '中文-新加坡',
    'zh-tw' => '中文-臺灣',
    'hr' => '克羅埃西亞語',
    'cs' => '捷克語',
    'da' => '丹麥語',
    'nl' => '荷蘭語',
    'nl-be' => '荷蘭語-比利時',
    'en' => '英語',
    'en-au' => '英語-澳大利亞',
    'en-bz' => '英語-貝里茲',
    'en-ca' => '英語-加拿大',
    'en-ie' => '英語-愛爾蘭',
    'en-jm' => '英語-牙買加',
    'en-nz' => '英語-紐西蘭',
    'en-za' => '英語-南非',
    'en-tt' => '英語-千里達',
    'en-gb' => '英語-大英國協',
    'en-us' => '英語-美國',
    'et' => '愛沙尼亞語',
    'fa' => '波斯語',
    'fi' => '芬蘭語',
    'fo' => '法羅群島語',
    'fr' => '法語-標準',
    'fr-be' => '法語-比利時',
    'fr-ca' => '法語-加拿大',
    'fr-lu' => '法語-盧森堡',
    'fr-ch' => '法語-瑞士',
    'gd' => '蓋爾語-蘇格蘭',
    'de' => '德語-標準',
    'de-at' => '德語-奧地利',
    'de-li' => '德語-列支敦斯登',
    'de-lu' => '德語-盧森堡',
    'de-ch' => '德語-瑞士',
    'el' => '希臘語',
    'he' => '希伯來語',
    'hi' => '印地語',
    'hu' => '匈牙利語',
    'is' => '冰島語',
    'in' => '印尼語',
    'it' => '義大利語-標準',
    'it-ch' => '義大利語-瑞士',
    'ja' => '日語',
    'ko' => '韓語',
    'lv' => '拉脫維亞語',
    'lt' => '立陶宛語',
    'mk' => '馬其頓語',
    'ms' => '馬來語-馬來西亞',
    'mt' => '馬爾他語',
    'no' => '挪威語-布克莫爾語',
    'pl' => '波蘭語',
    'pt' => '葡萄牙語-標準',
    'pt-br' => '葡萄牙語-巴西',
    'rm' => '利托-羅曼緒方言',
    'ro' => '羅馬尼亞語',
    'ro-mo' => '羅馬尼亞語-摩爾達維亞',
    'ru' => '俄語',
    'ru-mo' => '俄語-摩爾達維亞',
    'sr' => '塞爾維亞語-斯拉夫',
    'tn' => '波紮納語',
    'sl' => '斯洛維尼亞語',
    'sk' => '斯洛伐克語',
    'sb' => '索布語',
    'es' => '西班牙語-標準',
    'es-ar' => '西班牙語-阿根廷',
    'es-bo' => '西班牙語-玻利維亞',
    'es-cl' => '西班牙語-智利',
    'es-co' => '西班牙語-哥倫比亞',
    'es-cr' => '西班牙語-哥斯大黎加',
    'es-do' => '西班牙語-多明尼克共和國',
    'es-ec' => '西班牙語-厄瓜多',
    'es-gt' => '西班牙語-瓜地馬拉',
    'es-hn' => '西班牙語-宏都拉斯',
    'es-mx' => '西班牙語-墨西哥',
    'es-ni' => '西班牙語-尼加拉瓜',
    'es-pa' => '西班牙語-巴拿馬',
    'es-pe' => '西班牙語-秘魯',
    'es-pr' => '西班牙語-波多黎各',
    'es-py' => '西班牙語-巴拉圭',
    'es-sv' => '西班牙語-薩爾瓦多',
    'es-uy' => '西班牙語-烏拉圭',
    'es-ve' => '西班牙語-委內瑞拉',
    'sx' => '蘇圖語',
    'sv' => '瑞典語',
    'sv-fi' => '瑞典語-芬蘭',
    'th' => '泰語',
    'tr' => '土耳其語',
    'ts' => '聰加語',
    'uk' => '烏克蘭語',
    'ur' => '烏爾都語-巴基斯坦',
    'vi' => '越南語',
    'xh' => '科薩語',
    'ji' => '意第緒語',
    'zu' => '祖魯語',
);

$timezone = array(
    -1100 => array('label' => 'UTC-11:00',
        'Pacific/Midway' => '太平洋/中途島','Pacific/Niue' => '太平洋/紐埃','Pacific/Pago_Pago' => '太平洋/帕果帕果'),
    -1000 => array('label' => 'UTC-10:00',
        'America/Adak' => '美洲/埃達克','Pacific/Honolulu' => '太平洋/火奴魯魯','Pacific/Johnston' => '太平洋/約翰斯頓','Pacific/Rarotonga' => '太平洋/拉羅湯加島','Pacific/Tahiti' => '太平洋/塔希提島'),
    -930 => array('label' => 'UTC-09:30',
        'Pacific/Marquesas' => '太平洋/馬克薩斯'),
    -900 => array('label' => 'UTC-09:00',
        'America/Anchorage' => '美洲/安克雷奇','America/Juneau' => '美洲/朱諾','America/Metlakatla' => '美洲/Metlakatla','America/Nome' => '美洲/諾姆','America/Sitka' => '美洲/錫特卡','America/Yakutat' => '美洲/亞庫塔特','Pacific/Gambier' => '太平洋/甘比爾'),
    -800 => array('label' => 'UTC-08:00',
        'America/Dawson' => '美洲/道森','America/Los_Angeles' => '美洲/洛杉磯','America/Tijuana' => '美洲/蒂華納','America/Vancouver' => '美洲/溫哥華','America/Whitehorse' => '美洲/白馬','Pacific/Pitcairn' => '太平洋/皮特克恩'),
    -700 => array('label' => 'UTC-07:00',
        'America/Boise' => '美洲/博伊西','America/Cambridge_Bay' => '美洲/劍橋灣','America/Chihuahua' => '美洲/奇瓦瓦','America/Creston' => '美洲/克雷斯頓','America/Dawson_Creek' => '美洲/道森克里克','America/Denver' => '美洲/丹佛','America/Edmonton' => '美洲/埃德蒙頓','America/Fort_Nelson' => 'America/Fort_Nelson','America/Hermosillo' => '美洲/埃莫西','America/Inuvik' => '美洲/伊努維克','America/Mazatlan' => '美洲/馬薩特蘭','America/Ojinaga' => '美洲/Ojinaga','America/Phoenix' => '美洲/鳳凰城','America/Yellowknife' => '美洲/耶洛奈夫'),
    -600 => array('label' => 'UTC-06:00',
        'America/Bahia_Banderas' => '美洲/巴伊亞班德拉斯','America/Belize' => '美洲/伯利茲','America/Chicago' => '美洲/芝加哥','America/Costa_Rica' => '美洲/哥斯大黎加','America/El_Salvador' => '美洲/薩爾瓦多','America/Guatemala' => '美洲/瓜地馬拉','America/Indiana/Knox' => '美洲/印第安納州/諾克斯','America/Indiana/Tell_City' => '美洲/印第安納州/特爾城','America/Managua' => '美洲/馬那瓜','America/Matamoros' => '美洲/馬塔莫羅斯','America/Menominee' => '美洲/梅諾米尼','America/Merida' => '美洲/梅里達','America/Mexico_City' => '美洲/墨西哥城','America/Monterrey' => '美洲/蒙特雷','America/North_Dakota/Beulah' => '美洲/北達科他州/比尤拉','America/North_Dakota/Center' => '美洲/北達科他州/中心','America/North_Dakota/New_Salem' => '美洲/北達科他州/新塞勒姆','America/Rainy_River' => '美洲/雷尼里弗','America/Rankin_Inlet' => '美洲/蘭金因萊特','America/Regina' => '美洲/里賈納','America/Resolute' => '美洲/堅決','America/Swift_Current' => '美洲/斯威夫特卡倫特','America/Tegucigalpa' => '美洲/特古西加爾巴','America/Winnipeg' => '美洲/溫尼伯','Pacific/Galapagos' => '太平洋/加拉帕戈斯'),
    -500 => array('label' => 'UTC-05:00',
        'America/Atikokan' => '美洲/Atikokan','America/Bogota' => '美洲/波哥大','America/Cancun' => '美洲/坎昆','America/Cayman' => '美洲/開曼','America/Detroit' => '美洲/底特律','America/Eirunepe' => '美洲/Eirunepe','America/Guayaquil' => '美洲/瓜亞基爾','America/Havana' => '美洲/哈瓦那','America/Indiana/Indianapolis' => '美洲/印第安納州/印第安納波利斯','America/Indiana/Marengo' => '美洲/印第安納州/馬倫哥','America/Indiana/Petersburg' => '美洲/印第安納州/聖彼得堡','America/Indiana/Vevay' => '美洲/印第安納州/維維','America/Indiana/Vincennes' => '美洲/印第安納州/文森斯','America/Indiana/Winamac' => '美洲/印第安納州/威納馬克','America/Iqaluit' => '美洲/伊魁特','America/Jamaica' => '美洲/牙買加','America/Kentucky/Louisville' => '美洲/肯塔基州/路易斯維爾','America/Kentucky/Monticello' => '美洲/肯塔基州/蒙蒂塞洛','America/Lima' => '美洲/利馬','America/Nassau' => '美洲/拿騷','America/New_York' => '美洲/紐約','America/Nipigon' => '美洲/尼皮貢','America/Panama' => '美洲/巴拿馬','America/Pangnirtung' => '美洲/龐納唐','America/Port-au-Prince' => '美洲/太子港','America/Rio_Branco' => '美洲/里奧布朗庫','America/Thunder_Bay' => '美洲/桑德貝','America/Toronto' => '美洲/多倫多','Pacific/Easter' => '太平洋/復活島'),
    -400 => array('label' => 'UTC-04:00',
        'America/Anguilla' => '美洲/安圭拉','America/Antigua' => '美洲/安提瓜','America/Aruba' => '美洲/阿魯巴','America/Barbados' => '美洲/巴巴多斯','America/Blanc-Sablon' => '美洲/勒布朗','拉姆','America/Boa_Vista' => '美洲/博阿維斯塔','America/Caracas' => '美洲/加拉加斯','America/Curacao' => '美洲/庫拉索','America/Dominica' => '美洲/多米尼加','America/Glace_Bay' => '美洲/格萊斯貝','America/Goose_Bay' => '美洲/鵝灣','America/Grand_Turk' => '美洲/大特克島','America/Grenada' => '美洲/格林納達','America/Guadeloupe' => '美洲/瓜德羅普島','America/Guyana' => '美洲/圭亞那','America/Halifax' => '美洲/哈利法克斯','America/Kralendijk' => '美洲/克拉倫代克','America/La_Paz' => '美洲/拉巴斯','America/Lower_Princes' => '美洲/下王子','America/Manaus' => '美洲/馬瑙斯','America/Marigot' => '美洲/馬里戈特','America/Martinique' => '美洲/馬提尼克','America/Moncton' => '美洲/蒙克頓','America/Montserrat' => '美洲/蒙特塞拉特','America/Port_of_Spain' => '美洲/西班牙港','America/Porto_Velho' => '美洲/波多韋柳','America/Puerto_Rico' => '美洲/波多黎各','America/Santo_Domingo' => '美洲/聖多明各','America/St_Barthelemy' => '美洲/聖．繆','America/St_Kitts' => '美洲/聖．聖基茨','America/St_Lucia' => '美洲/聖．聖盧西亞','America/St_Thomas' => '美洲/聖．托馬斯','America/St_Vincent' => '美洲/聖．文森特','America/Thule' => '美洲/圖勒','America/Tortola' => '美洲/托爾托拉','Atlantic/Bermuda' => '大西洋/百慕達'),
    -330 => array('label' => 'UTC-03:30',
        'America/St_Johns' => '美洲/聖．約翰斯'),
    -300 => array('label' => 'UTC-03:00',
        'America/Araguaina' => '美洲/阿拉瓜伊納','America/Argentina/Buenos_Aires' => '美洲/阿根廷/布宜諾斯艾利斯','America/Argentina/Catamarca' => '美洲/阿根廷/卡塔馬卡','America/Argentina/Cordoba' => '美洲/阿根廷/科爾多瓦','America/Argentina/Jujuy' => '美洲/阿根廷/胡胡伊','America/Argentina/La_Rioja' => '美洲/阿根廷/拉里奧哈','America/Argentina/Mendoza' => '美洲/阿根廷/門多薩','America/Argentina/Rio_Gallegos' => '美洲/阿根廷/里奧加耶戈斯','America/Argentina/Salta' => '美洲/阿根廷/薩爾塔','America/Argentina/San_Juan' => '美洲/阿根廷/聖胡安','America/Argentina/San_Luis' => '美洲/阿根廷/聖路易斯','America/Argentina/Tucuman' => '美洲/阿根廷/圖庫曼','America/Argentina/Ushuaia' => '美洲/阿根廷/烏斯懷亞','America/Asuncion' => '美洲/亞松森','America/Bahia' => '美洲/巴伊亞','America/Belem' => '美洲/貝倫','America/Campo_Grande' => '美洲/大坎普','America/Cayenne' => '美洲/卡宴','America/Cuiaba' => '美洲/庫亞巴','America/Fortaleza' => '美洲/福塔雷薩','America/Godthab' => '美洲/哥特哈布','America/Maceio' => '美洲/馬塞約','America/Miquelon' => '美洲/密克隆群島','America/Montevideo' => '美洲/蒙得維的亞','America/Paramaribo' => '美洲/帕拉馬里博','America/Recife' => '美洲/累西腓','America/Santarem' => '美洲/聖塔倫','America/Santiago' => '美洲/聖地亞哥','Antarctica/Palmer' => '南極洲/帕爾默','Antarctica/Rothera' => '南極洲/羅西拉','Atlantic/Stanley' => '大西洋/斯坦利'),
    -200 => array('label' => 'UTC-02:00',
        'America/Noronha' => '美洲/迪諾羅尼亞','America/Sao_Paulo' => '美洲/聖保羅','Atlantic/South_Georgia' => '大西洋/南喬治亞'),
    -100 => array('label' => 'UTC-01:00',
        'America/Scoresbysund' => '美洲/斯科斯比松','Atlantic/Azores' => '大西洋/亞速爾群島','Atlantic/Cape_Verde' => '大西洋/佛得角'),
    +000 => array('label' => 'UTC+00:00',
        'UTC' => 'UTC','Africa/Abidjan' => '非洲/阿比讓','Africa/Accra' => '非洲/阿克拉','Africa/Bamako' => '非洲/巴馬科','Africa/Banjul' => '非洲/班珠爾','Africa/Bissau' => '非洲/比紹','Africa/Casablanca' => '非洲/卡薩布蘭卡','Africa/Conakry' => '非洲/科納克里','Africa/Dakar' => '非洲/達喀爾','Africa/El_Aaiun' => '非洲/阿尤恩','Africa/Freetown' => '非洲/弗里敦','Africa/Lome' => '非洲/洛美','Africa/Monrovia' => '非洲/蒙羅維亞','Africa/Nouakchott' => '非洲/努瓦克肖特','Africa/Ouagadougou' => '非洲/瓦加杜古','Africa/Sao_Tome' => '非洲/聖多美','America/Danmarkshavn' => '美洲/丹馬沙','Antarctica/Troll' => 'Antarctica/Troll','Atlantic/Canary' => '大西洋/加那利','Atlantic/Faroe' => '大西洋/法羅','Atlantic/Madeira' => '大西洋/馬德拉','Atlantic/Reykjavik' => '大西洋/雷克雅未克','Atlantic/St_Helena' => '大西洋/聖．海倫娜','Europe/Dublin' => '歐洲/都柏林','Europe/Guernsey' => '歐洲/根西島','Europe/Isle_of_Man' => '歐洲/馬恩島','Europe/Jersey' => '歐洲/新澤西','Europe/Lisbon' => '歐洲/里斯本','Europe/London' => '歐洲/倫敦'),
    +100 => array('label' => 'UTC+01:00',
        'Africa/Algiers' => '非洲/阿爾及爾','Africa/Bangui' => '非洲/班吉','Africa/Brazzaville' => '非洲/布拉柴維爾','Africa/Ceuta' => '非洲/休達','Africa/Douala' => '非洲/杜阿拉','Africa/Kinshasa' => '非洲/金沙薩','Africa/Lagos' => '非洲/拉各斯','Africa/Libreville' => '非洲/利伯維爾','Africa/Luanda' => '非洲/羅安達','Africa/Malabo' => '非洲/馬拉博','Africa/Ndjamena' => '非洲/恩賈梅納','Africa/Niamey' => '非洲/尼亞美','Africa/Porto-Novo' => '非洲/波多諾伏','Africa/Tunis' => '非洲/突尼斯','Arctic/Longyearbyen' => '北極/朗伊爾城','Europe/Amsterdam' => '歐洲/阿姆斯特丹','Europe/Andorra' => '歐洲/安道爾','Europe/Belgrade' => '歐洲/貝爾格萊德','Europe/Berlin' => '歐洲/柏林','Europe/Bratislava' => '歐洲/布拉迪斯拉發','Europe/Brussels' => '歐洲/布魯塞爾','Europe/Budapest' => '歐洲/布達佩斯','Europe/Busingen' => '歐洲/布辛根','Europe/Copenhagen' => '歐洲/哥本哈根','Europe/Gibraltar' => '歐洲/直布羅陀','Europe/Ljubljana' => '歐洲/盧布爾雅那','Europe/Luxembourg' => '歐洲/盧森堡','Europe/Madrid' => '歐洲/馬德里','Europe/Malta' => '歐洲/馬耳他','Europe/Monaco' => '歐洲/摩納哥','Europe/Oslo' => '歐洲/奧斯陸','Europe/Paris' => '歐洲/巴黎','Europe/Podgorica' => '歐洲/波德戈里察','Europe/Prague' => '歐洲/布拉格','Europe/Rome' => '歐洲/羅馬','Europe/San_Marino' => '歐洲/聖馬力諾','Europe/Sarajevo' => '歐洲/薩拉熱窩','Europe/Skopje' => '歐洲/斯科普里','Europe/Stockholm' => '歐洲/斯德哥爾摩','Europe/Tirane' => '歐洲/地拉那','Europe/Vaduz' => '歐洲/瓦杜茲','Europe/Vatican' => '歐洲/梵蒂岡','Europe/Vienna' => '歐洲/維也納','Europe/Warsaw' => '歐洲/華沙','Europe/Zagreb' => '歐洲/薩格勒布','Europe/Zurich' => '歐洲/蘇黎世'),
    +200 => array('label' => 'UTC+02:00',
        'Africa/Blantyre' => '非洲/布蘭太爾','Africa/Bujumbura' => '非洲/布瓊布拉','Africa/Cairo' => '非洲/開羅','Africa/Gaborone' => '非洲/哈博羅內','Africa/Harare' => '非洲/哈拉雷','Africa/Johannesburg' => '非洲/約翰尼斯堡','Africa/Kigali' => '非洲/基加利','Africa/Lubumbashi' => '非洲/盧本巴希','Africa/Lusaka' => '非洲/盧薩卡','Africa/Maputo' => '非洲/馬普托','Africa/Maseru' => '非洲/馬塞盧','Africa/Mbabane' => '非洲/姆巴巴內','Africa/Tripoli' => '非洲/的黎波里','Africa/Windhoek' => '非洲/溫得和克','Asia/Amman' => '亞洲/安曼','Asia/Beirut' => '亞洲/貝魯特','Asia/Damascus' => '亞洲/大馬士革','Asia/Gaza' => '亞洲/加沙','Asia/Hebron' => '亞洲/希伯倫','Asia/Jerusalem' => '亞洲/耶路撒冷','Asia/Nicosia' => '亞洲/尼科西亞','Europe/Athens' => '歐洲/雅典','Europe/Bucharest' => '歐洲/布加勒斯特','Europe/Chisinau' => '歐洲/基希訥烏','Europe/Helsinki' => '歐洲/赫爾辛基','Europe/Istanbul' => '歐洲/伊斯坦布爾','Europe/Kaliningrad' => '歐洲/加里寧格勒','Europe/Kiev' => '歐洲/基輔','Europe/Mariehamn' => '歐洲/瑪麗港','Europe/Riga' => '歐洲/裡加','Europe/Sofia' => '歐洲/索非亞','Europe/Tallinn' => '歐洲/塔林','Europe/Uzhgorod' => '歐洲/烏日哥羅德','Europe/Vilnius' => '歐洲/維爾紐斯','Europe/Zaporozhye' => '歐洲/扎波羅熱'),
    +300 => array('label' => 'UTC+03:00',
        'Africa/Addis_Ababa' => '非洲/亞的斯亞貝巴','Africa/Asmara' => '非洲/阿斯馬拉','Africa/Dar_es_Salaam' => '非洲/達累斯薩拉姆','Africa/Djibouti' => '非洲/吉布提','Africa/Juba' => '非洲/朱巴','Africa/Kampala' => '非洲/坎培拉','Africa/Khartoum' => '非洲/喀土穆','Africa/Mogadishu' => '非洲/摩加迪沙','Africa/Nairobi' => '非洲/內羅畢','Antarctica/Syowa' => '南極洲/昭和','Asia/Aden' => '亞洲/亞丁','Asia/Baghdad' => '亞洲/巴格達','Asia/Bahrain' => '亞洲/巴林','Asia/Kuwait' => '亞洲/科威特','Asia/Qatar' => '亞洲/卡塔爾','Asia/Riyadh' => '亞洲/利雅得','Europe/Kirov' => 'Europe/Kirov','Europe/Minsk' => '歐洲/明斯克','Europe/Moscow' => '歐洲/莫斯科','Europe/Simferopol' => '歐洲/辛菲羅波爾','Europe/Volgograd' => '歐洲/伏爾加格勒','Indian/Antananarivo' => '印度/塔那那利佛','Indian/Comoro' => '印度/科摩羅','Indian/Mayotte' => '印度/馬約特島'),
    +330 => array('label' => 'UTC+03:30',
        'Asia/Tehran' => '亞洲/德黑蘭'),
    +400 => array('label' => 'UTC+04:00',
        'Asia/Baku' => '亞洲/巴庫','Asia/Dubai' => '亞洲/杜拜','Asia/Muscat' => '亞洲/馬斯喀特','Asia/Tbilisi' => '亞洲/第比利斯','Asia/Yerevan' => '亞洲/埃里溫','Europe/Astrakhan' => 'Europe/Astrakhan','Europe/Samara' => '歐洲/薩馬拉','Europe/Ulyanovsk' => 'Europe/Ulyanovsk','Indian/Mahe' => '印度/馬埃','Indian/Mauritius' => '印度/毛里求斯','Indian/Reunion' => '印度/留尼汪'),
    +430 => array('label' => 'UTC+04:30',
        'Asia/Kabul' => '亞洲/喀布爾'),
    +500 => array('label' => 'UTC+05:00',
        'Antarctica/Mawson' => '南極洲/莫森','Asia/Aqtau' => '亞洲/阿克陶','Asia/Aqtobe' => '亞洲/阿克托別','Asia/Ashgabat' => '亞洲/阿什哈巴德','Asia/Dushanbe' => '亞洲/杜尚別','Asia/Karachi' => '亞洲/卡拉奇','Asia/Oral' => '亞洲/西哈薩克斯坦','Asia/Samarkand' => '亞洲/撒馬爾罕','Asia/Tashkent' => '亞洲/塔什幹','Asia/Yekaterinburg' => '亞洲/葉卡捷琳堡','Indian/Kerguelen' => '印度/凱爾蓋朗','Indian/Maldives' => '印度/馬爾地夫'),
    +530 => array('label' => 'UTC+05:30',
        'Asia/Colombo' => '亞洲/科倫坡','Asia/Kolkata' => '亞洲/加爾各答'),
    +545 => array('label' => 'UTC+05:45',
        'Asia/Kathmandu' => '亞洲/加德滿都'),
    +600 => array('label' => 'UTC+06:00',
        'Antarctica/Vostok' => '南極洲/東方','Asia/Almaty' => '亞洲/阿拉木圖','Asia/Bishkek' => '亞洲/比什凱克','Asia/Dhaka' => '亞洲/達卡','Asia/Omsk' => '亞洲/鄂木斯克','Asia/Qyzylorda' => '亞洲/克孜勒奧爾達','Asia/Thimphu' => '亞洲/廷布','Asia/Urumqi' => '亞洲/烏魯木齊','Indian/Chagos' => '印度/查戈斯'),
    +630 => array('label' => 'UTC+06:30',
        'Asia/Rangoon' => '亞洲/仰光','Indian/Cocos' => '印度/科科斯'),
    +700 => array('label' => 'UTC+07:00',
        'Antarctica/Davis' => '南極洲/戴維斯','Asia/Bangkok' => '亞洲/曼谷','Asia/Barnaul' => 'Asia/Barnaul','Asia/Ho_Chi_Minh' => '亞洲/胡志明','Asia/Hovd' => '亞洲/科布多','Asia/Jakarta' => '亞洲/雅加達','Asia/Krasnoyarsk' => '亞洲/克拉斯諾亞爾斯克','Asia/Novokuznetsk' => '亞洲/新庫茲涅茨克','Asia/Novosibirsk' => '亞洲/新西伯利亞','Asia/Phnom_Penh' => '亞洲/金邊','Asia/Pontianak' => '亞洲/坤甸','Asia/Tomsk' => 'Asia/Tomsk','Asia/Vientiane' => '亞洲/萬象','Indian/Christmas' => '印度/聖誕'),
    +800 => array('label' => 'UTC+08:00',
        'Antarctica/Casey' => '南極洲/凱西','Asia/Brunei' => '亞洲/文萊','Asia/Choibalsan' => '亞洲/喬巴山','Asia/Hong_Kong' => '亞洲/香港','Asia/Irkutsk' => '亞洲/伊爾庫茨克','Asia/Kuala_Lumpur' => '亞洲/吉隆坡','Asia/Kuching' => '亞洲/古晉','Asia/Macau' => '亞洲/澳門','Asia/Makassar' => '亞洲/望加錫','Asia/Manila' => '亞洲/馬尼拉','Asia/Shanghai' => '亞洲/上海','Asia/Singapore' => '亞洲/新加坡','Asia/Taipei' => '亞洲/台北','Asia/Ulaanbaatar' => '亞洲/烏蘭巴托','Australia/Perth' => '澳洲/珀斯'),
    +830 => array('label' => 'UTC+08:30',
        'Asia/Pyongyang' => '亞洲/平壤'),
    +845 => array('label' => 'UTC+08:45',
        'Australia/Eucla' => '澳洲/尤克拉'),
    +900 => array('label' => 'UTC+09:00',
        'Asia/Chita' => 'Asia/Chita','Asia/Dili' => '亞洲/帝力','Asia/Jayapura' => '亞洲/查亞普拉','Asia/Khandyga' => '亞洲/ Khandyga','Asia/Seoul' => '亞洲/首爾','Asia/Tokyo' => '亞洲/東京','Asia/Yakutsk' => '亞洲/雅庫茨克','Pacific/Palau' => '太平洋/帛琉'),
    +930 => array('label' => 'UTC+09:30',
        'Australia/Darwin' => '澳洲/達爾文'),
    +1000 => array('label' => 'UTC+10:00',
        'Antarctica/DumontDUrville' => '南極洲/迪蒙迪維爾站','Asia/Ust-Nera' => '亞洲/烏斯季挪拉','Asia/Vladivostok' => '亞洲/符拉迪沃斯托克','Australia/Brisbane' => '澳洲/布里斯班','Australia/Lindeman' => '澳洲/林德曼','Pacific/Chuuk' => '太平洋/特魯克','Pacific/Guam' => '太平洋/關島','Pacific/Port_Moresby' => '太平洋/莫爾茲比港','Pacific/Saipan' => '太平洋/塞班島'),
    +1030 => array('label' => 'UTC+10:30',
        'Australia/Adelaide' => '澳洲/阿德萊德','Australia/Broken_Hill' => '澳洲/斷山'),
    +1100 => array('label' => 'UTC+11:00',
        'Antarctica/Macquarie' => '南極洲/麥格理','Asia/Magadan' => '亞洲/馬加丹','Asia/Sakhalin' => '亞洲/薩哈林','Asia/Srednekolymsk' => 'Asia/Srednekolymsk','Australia/Currie' => '澳洲/柯里','Australia/Hobart' => '澳洲/霍巴特','Australia/Lord_Howe' => '澳洲/豪勳爵','Australia/Melbourne' => '澳洲/墨爾本','Australia/Sydney' => '澳洲/雪梨','Pacific/Bougainville' => 'Pacific/Bougainville','Pacific/Efate' => '太平洋/埃法特島','Pacific/Guadalcanal' => '太平洋/瓜達爾卡納爾島','Pacific/Kosrae' => '太平洋/科斯雷','Pacific/Norfolk' => '太平洋/諾福克','Pacific/Noumea' => '太平洋/努美阿','Pacific/Pohnpei' => '太平洋/波納佩'),
    +1200 => array('label' => 'UTC+12:00',
        'Asia/Anadyr' => '亞洲/阿納德爾','Asia/Kamchatka' => '亞洲/堪察加','Pacific/Fiji' => '太平洋/斐濟','Pacific/Funafuti' => '太平洋/富納富提','Pacific/Kwajalein' => '太平洋/誇賈林','Pacific/Majuro' => '太平洋/馬朱羅','Pacific/Nauru' => '太平洋/瑙魯','Pacific/Tarawa' => '太平洋/塔拉瓦','Pacific/Wake' => '太平洋/威克島','Pacific/Wallis' => '太平洋/沃利斯'),
    +1300 => array('label' => 'UTC+13:00',
        'Antarctica/McMurdo' => '南極洲/麥克默多','Pacific/Auckland' => '太平洋/奧克蘭','Pacific/Enderbury' => '太平洋/恩德貝里','Pacific/Fakaofo' => '太平洋/法考福','Pacific/Tongatapu' => '太平洋/湯加塔布'),
    +1345 => array('label' => 'UTC+13:45',
        'Pacific/Chatham' => '太平洋/查塔姆'),
    +1400 => array('label' => 'UTC+14:00',
        'Pacific/Apia' => '太平洋/阿皮亞','Pacific/Kiritimati' => '太平洋/克里斯馬斯'),
);
